DEFRA/adp-portal-api

.azuredevops/build.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
[AB#336334](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/336334)
1. construct container app name, managed identity and variable group names based on the app name.
2. Use <environment> string in variable groups instead of env names
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=502378&view=results
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.
=> 336334: Container App Name

.azuredevops/build.yaml, .azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
[AB#341033](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/341033)
sharedAppRegServicePrincipal added to remove the hardcoding
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=510144&view=results
=> 341033: Portal API env variable update

.azuredevops/build.yaml, .azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
[AB#341033](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/341033)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=510367&view=results
=> 341033: parameterized git-repo-org

.devcontainer/devcontainer.json, src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Mapster/FluxTeamConfigMappings.cs, src/ADP.Portal.Api/Models/Flux/ServiceFluxConfigRequest.cs, test/ADP.Portal.Core.Tests/Git/Services/GitOpsFluxTeamConfigServiceTests.cs
Adds a dev container for local development, and makes a few tweaks to the endpoint for adding services to the flux config.
[AB#345221](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/345221)
=> 345221: Updates to the flux config services api

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
Added config for AzureAd__TenantName config for poral API app.
[AB#305682](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305682)
=> 305682:Add AzureAd TenantName config

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/AadGroupController.cs, src/ADP.Portal.Api/Controllers/AdoProjectController.cs, src/ADP.Portal.Api/Controllers/FluxTeamConfigController.cs, src/ADP.Portal.Api/Program.cs
Set Ingress external flag to true to allow access with in the network. 
Fixed vulnerabilities in the API. 
Changed URLs in the AadGroup controller. 
=> 305668: API allow external

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/AadGroupController.cs, src/ADP.Portal.Api/Controllers/AdoProjectController.cs, src/ADP.Portal.Api/Controllers/FluxTeamConfigController.cs, src/ADP.Portal.Api/Controllers/GithubTeamsController.cs, src/ADP.Portal.Api/Models/Github/SyncTeamRequest.cs, src/ADP.Portal.Api/Program.cs, src/ADP.Portal.Core/Git/Entities/GitHubOptions.cs, src/ADP.Portal.Core/Git/Entities/GithubTeamDetails.cs, src/ADP.Portal.Core/Git/Entities/GithubTeamUpdate.cs, src/ADP.Portal.Core/Git/Services/GitHubService.cs, src/ADP.Portal.Core/Git/Services/IGitHubService.cs, test/ADP.Portal.Api.Tests/ADP.Portal.Api.Tests.csproj, test/ADP.Portal.Api.Tests/Controllers/GitHubTeamControllerTests.cs, test/ADP.Portal.Core.Tests/ADP.Portal.Core.Tests.csproj, test/ADP.Portal.Core.Tests/Git/Services/GitHubServiceTests.cs
Adds an endpoint to sync a team in github
[AB#358695](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/358695)
=> 358695: Sync github team

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/AadGroupController.cs, src/ADP.Portal.Api/Controllers/FluxTeamConfigController.cs, src/ADP.Portal.Api/Mapster/FluxTeamConfigMappings.cs, src/ADP.Portal.Core/Git/Services/GitOpsFluxTeamConfigService.cs, src/ADP.Portal.Core/Git/Services/IGitOpsFluxTeamConfigService.cs, test/ADP.Portal.Api.Tests/Controllers/FluxTeamConfigControllerTests.cs, test/ADP.Portal.Core.Tests/Git/Services/GitOpsFluxTeamConfigServiceTests.cs
Added a new endpoint to add environmet for a service.
=> 305668:Flux service environment

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/GithubTeamsController.cs, src/ADP.Portal.Api/Models/Github/SyncTeamRequest.cs, src/ADP.Portal.Core/Git/Entities/GithubTeamUpdate.cs, src/ADP.Portal.Core/Git/Services/GitHubService.cs, src/ADP.Portal.Core/Git/Services/IGitHubService.cs, test/ADP.Portal.Api.Tests/Controllers/GitHubTeamControllerTests.cs, test/ADP.Portal.Core.Tests/Git/Services/GitHubServiceTests.cs
[AB#358695](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/358695)
This updated the team sync endpoint to use an id to identify a team, rather than inferring it from the team name
=> 358695: Update github team sync endpoints

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/FluxTeamConfigController.cs, src/ADP.Portal.Api/Controllers/GithubTeamsController.cs, src/ADP.Portal.Core/Git/Services/GitHubService.cs, src/ADP.Portal.Core/Git/Services/GitOpsFluxTeamConfigService.cs
Fixed sonar issues
[AB#350742](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/350742)
=> 350742: Sonar fixes

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
Description
Updated config for templates repo config. 
=> 305668:Templates repo config

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Infrastructure/GitHubRepository.cs
=> 305668:Fixed serializer issue

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Services/FluxTeamConfigService.cs
=> 305668: Create environment files fix

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
Updated flux templates version  to 1.0.1
=> 305668:Updated flux templates version

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Extensions/FluxTemplateExtensions.cs, src/ADP.Portal.Core/Git/Services/FluxTeamConfigService.cs
Add deep copy for the templates read from cache.
Relates to ADO Work Item [AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)
N/A
N/A
=> 305668: Add deep copy for the templates read from cache.

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Entities/Constants.cs, src/ADP.Portal.Core/Git/Services/FluxTeamConfigService.cs, src/ADP.Portal.Core/Helpers/YamlQuery.cs, test/ADP.Portal.Core.Tests/Git/Services/FluxTeamConfigServiceTests.cs
Added ingress config for forntend service and onbard new team.
=> 305668: Added ingress config

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Entities/Constants.cs
Updated the INGRESS_ENDPOINT toke key
=> 305668:Updated the INGRESS_ENDPOINT token key

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Services/GitHubService.cs
Fixes an issue where team members would be toggled. This was caused by the username checks being case sensitive, while github is case insensitive
=> Github usernames are case insensitive.

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Services/GitHubService.cs, test/ADP.Portal.Core.Tests/Git/Services/GitHubServiceTests.cs
[AB#381946](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/381946) Add a check to make sure that all the users being added to a team are already part of the organisation.
=> 381946: Ignore users who are not part of the github organisation

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Entities/Constants.cs
Fixed ACR name in predeploy migration patch image
[AB#385406](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/385406)
=> 385406: Fixed ACR name in predeploy migration patch image

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
Updated FluxTemplatesGitRepo__Reference to 1.0.2
Relates to ADO Work Item [AB#383608](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383608)
Depends on PR https://github.com/DEFRA/adp-flux-templates/pull/5
=> 383608: Updated FluxTemplatesGitRepo__Reference to 1.0.4

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/GithubTeamsController.cs, src/ADP.Portal.Api/Program.cs, src/ADP.Portal.Api/Properties/launchSettings.json, src/ADP.Portal.Api/appsettings.Development.json
[AB#353928](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/353928) adds validation checks to the jwt token to ensure that only valid users are calling the api.
The scheme was only added to the github teams api for now, as that is not being called by the pipelines. A future PR will add in the auth for the other endpoints.
=> 353928: Add jwt bearer validation 

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Program.cs, src/ADP.Portal.Core/Git/Services/CacheService.cs, test/ADP.Portal.Core.Tests/Git/Services/CacheServicesTests.cs
[AB#353928](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/353928) add some unit tests to increase the coverage and allow the build to succeed
=> 353928: Add unit tests to improve coverage

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Services/FluxTeamConfigService.cs, test/ADP.Portal.Core.Tests/Git/Services/FluxTeamConfigServiceTests.cs
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#XXX and builds on #3376 (link to ADO Build ID URL)*
=> Fix the key issue for helm only generate

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/GithubTeamsController.cs
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#XXX and builds on #3376 (link to ADO Build ID URL)*
=> Disbale Auth

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
Update Flux Template version
Relates to ADO Work Item [AB#383702](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383702)
N/A
N/A
=> 383702: Update Flux Template version

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Infrastructure/GitHubRepository.cs, src/ADP.Portal.Core/Git/Services/FluxTeamConfigService.cs, test/ADP.Portal.Core.Tests/Git/Services/FluxTeamConfigServiceTests.cs
Commit flux changes into main brranch. 
=> Commit flux manifest to main branch

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/appsettings.Development.json, src/ADP.Portal.Core/Git/Entities/GitHubOptions.cs, src/ADP.Portal.Core/Git/Services/GitHubService.cs, test/ADP.Portal.Core.Tests/Git/Services/GitHubServiceTests.cs
Adds some logging to make it more clear why a team was not adopted
=> Add logging around github team adoption

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/ADP.Portal.Api.http, src/ADP.Portal.Api/appsettings.Development.json, src/ADP.Portal.Core/Git/Entities/Constants.cs, src/ADP.Portal.Core/Git/Services/FluxTeamConfigService.cs, test/ADP.Portal.Core.Tests/Git/Services/FluxTeamConfigServiceTests.cs
Fix for helm only manifests generation
[AB#393544](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/393544)
=> 393544: Fix for helm only manifests generation

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/appsettings.Development.json, src/ADP.Portal.Core/Git/Entities/FluxImagePolicy.cs, src/ADP.Portal.Core/Git/Entities/FluxImagePolicyRegex.cs, src/ADP.Portal.Core/Git/Infrastructure/GitHubRepository.cs, src/ADP.Portal.Core/Git/Infrastructure/IGitHubRepository.cs, src/ADP.Portal.Core/Git/Services/FluxTeamConfigService.cs, src/ADP.Portal.Core/Git/Services/GroupsConfigService.cs, test/ADP.Portal.Core.Tests/Git/Infrastructure/GitHubRepositoryTests.cs, test/ADP.Portal.Core.Tests/Git/Services/FluxTeamConfigServiceTests.cs, test/ADP.Portal.Core.Tests/Git/Services/GroupsConfigServiceTests.cs
Keep the latest flux image policy version on the flux manifest generation.
=> Flux image versions

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/GithubTeamsController.cs
[AB#353928](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/353928) Turns the authentication back on.
=> 353928: Enable authentication

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/appsettings.Development.json
Updated adp-flux-templates release version to 1.0.10. 
Flux template changes include:
- Updated job max CPU limit to 500m to match the container max CPU limit
[AB#395979](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/395979)
To be merged after the PR https://github.com/DEFRA/adp-flux-templates/pull/13 is completed and release 1.0.10 is created
=> 395979: Updated adp-flux-templates release version to 1.0.10

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/GithubTeamsController.cs
[AB#382055](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/382055) Disables auth for now. Will need to be reworked in a future PR due to different tokens being sent across now.
=> 382055: Disable auth for now

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/AadGroupController.cs, src/ADP.Portal.Api/Controllers/FluxTeamConfigController.cs
Enrich error logs with error content
[AB#399252](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399252)
=> 399252: Enrich error logs with error content

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/AadGroupController.cs, src/ADP.Portal.Core/Git/Services/GroupsConfigService.cs, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defra.yml, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defradev.yml, test/ADP.Portal.Api.Tests/Controllers/AadGroupControllerTests.cs, test/ADP.Portal.Core.Tests/Git/Services/GroupsConfigServiceTests.cs
[AB#394807](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/394807) 
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=600584&view=results
=> 394807 : OpenVPN Group

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Program.cs, src/ADP.Portal.Api/appsettings.Development.json, src/ADP.Portal.Core/Git/Services/GroupsConfigService.cs, test/ADP.Portal.Core.Tests/Git/Services/GroupsConfigServiceTests.cs
Pass in the platform engineers group name through config as it is a different name in dev/tst vs pre/prd
=> Parameterize platform engineers team

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/ADP.Portal.Api.http, src/ADP.Portal.Api/Controllers/AdoProjectController.cs, src/ADP.Portal.Core/Ado/Infrastructure/AdoService.cs, test/ADP.Portal.Core.Tests/Ado/Infrastructure/AdoServiceTests.cs
Skip the service connection creation if it already exists in the target ADO project.
Relates to ADO Work Item AB#XXX
N/A
N/A
=> Skip the service connection creation if it already exists in the target ADO project.

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/Services/GroupsConfigService.cs, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defra.yml, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defradev.yml
Added an Accessgroup for granting project team access to Azure resources. TechUsers and Admin User groups are the members of this group.
Relates to ADO Work Item [AB#305099](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305099)
=> 305099: Added an Accessgroup for granting project team access to Azure resources

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defra.yml, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defradev.yml
Added Resources-Reader Access group
Relates to ADO Work Item [AB#305099](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305099)
=> 305099: Added Resources-Reader Access group

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defra.yml
[AB#412308](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/412308)
=> 412308: DEV1-AKS-Cluster-Custom-Resources-Reader for tech and admin users

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defra.yml, src/ADP.Portal.Core/Git/template/UserGroupMemberShip.defradev.yml
*Link to the relevant work items:*
[AB#406831](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/406831)
[AB#409694](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/409694)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=614489&view=results
=> 406831: Add Reader and writer for teams

.azuredevops/containerApp.yaml, src/ADP.Portal.Api/ADP.Portal.Api.csproj
Updated flux-templates version to 1.0.11
[AB#408229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/408229)
=> 408229: Update flux templates version to 1.0.11

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/FluxTeamConfigController.cs
Generate manifests set default environment base on the tenant name.
[AB#408229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/408229)
=> 408229: Generate manifests default env

src/ADP.Portal.Api/ADP.Portal.Api.csproj, src/ADP.Portal.Api/Controllers/AadGroupController.cs
Added Pipeline Auth scheme in SyncgroupApi.
This will authorize Pipeline to call '{teamName}/sync' api to sync existing teams with new access groups.
Relates to ADO Work Item [AB#415630](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/415630)
=> 415630: Added Pipeline Auth schem in SyncGroupsForTeam Api
